trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: none 

- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: AzureMysqlDeployment@1
  displayName: 'Execute Azure MySQL : InlineSqlTask'
  inputs:
    ConnectedServiceName: $(ConnectedServiceName)
    ServerName: $(ServerName)
    DatabaseName: schema1
    SqlUsername: $(SqlUserName)
    SqlPassword: $(SqlPassword)
    TaskNameSelector: InlineSqlTask
    SqlInline: SELECT * FROM schema1.table1;
